"""empty message

Revision ID: 241600f5e906
Revises: fe22dc581005
Create Date: 2022-09-03 15:24:03.010829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '241600f5e906'
down_revision = 'fe22dc581005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('full_name', sa.String(length=30), nullable=False))
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('contact', 'full_name')
    # ### end Alembic commands ###
