"""empty message

Revision ID: 77662e65cb70
Revises: f4ec3e62fac9
Create Date: 2022-09-03 15:03:20.224690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77662e65cb70'
down_revision = 'f4ec3e62fac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'budget')
    op.drop_column('contact', 'services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('services', mysql.VARCHAR(length=3), nullable=True))
    op.add_column('contact', sa.Column('budget', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
