"""empty message

Revision ID: bb2af92575be
Revises: 6054d743c1a8
Create Date: 2022-09-02 18:02:32.689678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2af92575be'
down_revision = '6054d743c1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact__',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('services', sa.String(length=3), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact__')
    # ### end Alembic commands ###
