"""empty message

Revision ID: fe22dc581005
Revises: c9deb40d404d
Create Date: 2022-09-03 15:18:47.641163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe22dc581005'
down_revision = 'c9deb40d404d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_column('contact', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('full_name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###
